### ISSUE TITLE
php and go script should take option for temperature and hunidity calibration

### ISSUE THREAD

**Issue by mcsage** [mreymann/temperx#1]
Your scripts are working very well but unfortunatelly my sensor has an offset between real and measured temperature.
An option for calibration both temperature and humidity would be an great enhancement.

**Comment by mreymann** [comment]
The PHP Munin plugin now has calibration options. The Go version will take a while ... Stay tuned. ;-)

**Comment by mreymann** [comment]
The Go tool now also has calibration options. Please give it a try.
