### ISSUE TITLE
Should the humidity always be 200 on a 413d:2107 device?

### ISSUE THREAD

**Issue by hi2u** [mreymann/temperx#3]
Hi, sorry to post this question as an issue... it's probably not a bug report.

I've got a `413d:2107` device, which looks like this: https://pcsensor.com/images/source/New_TEMPer/New_TEMPer_8.jpg

And I'm using your PHP script to read temps from it.  Thanks!  It's the only thing I could get working with it.

Regarding the humidity reading...

```php
echo "y1.value $hum\n";
```

Mine always reports a value of `200` at all times.  The temperature varies though.

Do you know if this value should vary on this device?  Or is the code just there for other devices?

Is there anything I can try to get the humidity working?  

I'm not even sure if the device has the feature or not?  I didn't see any mention of humidity on Ebay or Amazon for this device - but yours seem to also have code `413d:2107`?

**Comment by mreymann** [comment]
Unfortunately there are many different devices that use this vendor ID. Mine looks like this: https://www.modmypi.com/raspberry-pi/sensors-1061/temperaturepressurehumidity-1066/temperhum-usb-temperature-and-humidity-sensor
Yours maybe has no humidity sensor built in.

**Comment by hi2u** [comment]
Ok that makes sense then, mine most likely doesn't have a humidity sensor in that case.

Thanks for getting back to me!
